debug:
  enabled: true
proxy:
  # use "openssl rand -hex 32" to generate a suitable token
  secretToken: ""
  service:
    # Set type to NodePort to avoid trying to create a loadbalancer
    type: "NodePort"
    nodePorts:
      http: 30080
      https: 30443
auth:
  type: custom
  custom:
    className: oauthenticator.generic.GenericOAuthenticator
    config:
      login_service: "EGI Check-in"
      client_id: "8d5b193b-14a6-474b-bf2c-9b3a4a3bfb44"
      client_secret: ""
      token_url: https://aai.egi.eu/oidc/token
      userdata_url: https://aai.egi.eu/oidc/userinfo
      userdata_method: GET
      userdata_params: {'state': 'state', 'scope': 'openid profile email eduperson_entitlement'}
      username_key: sub
hub:
  image:
    name: 192.168.140.29:5000/k8s-custom-hub
    tag: '0.8.0.1'
  baseUrl: /
  extraEnv:
    OAUTH2_AUTHORIZE_URL: https://aai.egi.eu/oidc/authorize
    OAUTH2_TOKEN_URL: https://aai.egi.eu/oidc/token
    OAUTH_CALLBACK_URL: https://jupyter.lsst.ac.uk/hub/oauth_callback
    MY_GROUP: "^urn:mace:egi.eu:group:registry:UKLSST:role=member"
    # use "openssl rand -hex 32" to generate a suitable token
    JUPYTERHUB_CRYPT_KEY: ""
  extraConfig:
    # Custom spawner class
    # - Includes form option to select image to use
    # - Includes form option to select cpu/memory limits
    custom_spawn: |
      from kubespawner.spawner import KubeSpawner
      from traitlets import observe
      from time import time
      from nacl import encoding
      from nacl import signing
      class MySpawner(KubeSpawner):
        @observe('user_options')
        def _update_options(self, change):
          options = change.new
          if 'image' in options:
            self.singleuser_image_spec = options['image']
          if 'mem' in options:
            self.mem_guarantee = options['mem']
            self.mem_limit = options['mem']
          if 'cpu' in options:
            self.cpu_guarantee = options['cpu']
            self.cpu_limit = options['cpu']
        def options_from_form(self, formdata):
          images = {
            0: "192.168.140.29:5000/ztf-notebook:0.0.7",
            1: "jupyter/base-notebook",
            2: "jupyter/datascience-notebook",
          }
          mems = {
            0: "256M",
            1: "1G",
            2: "8G",
            3: "24G"
          }
          cpus = {
            0: 0.25,
            1: 1.0,
            2: 4.0,
            3: 12.0
          }
          options = {}
          img = 0
          size = 0
          try:
            img = int(formdata.get('image', [''])[0])
          except ValueError:
            pass
          options['image'] = images.get(img, images[0])
          try:
            size = int(formdata.get('size', [''])[0])
          except ValueError:
            pass
          options['mem'] = mems.get(size, mems[1])
          options['cpu'] = cpus.get(size, cpus[1])
          return options
        def send_acct(self, data, id=None):
          signing_key_hex = ""
          if id:
            method = "PUT"
            url = 'http://192.168.140.14:5000/job/%s' % (id)
          else:
            method = "POST"
            url = 'http://192.168.140.14:5000/job'
          self.log.info("Sending accounting data %s %s %s" % (method, url, str(data)))
          signing_key = signing.SigningKey(signing_key_hex, encoder=encoding.HexEncoder)
          sig = encoding.URLSafeBase64Encoder.encode(signing_key.sign(data).signature)
          self.log.info("Accounting signature %s" % (sig))
          req = request.Request(url=url, data=data, method=method)
          req.add_header("Content-Type", "application/json")
          req.add_header("X-Signature", sig)
          with request.urlopen(req) as f:
            return f.read(256).decode('utf-8')
          # TODO: catch errors and log
        def start(self):
          r = super().start()
          id = self.environment['JOB_ID']
          #url = 'http://192.168.140.14:5000/job/%s' % (id)
          message = '{ "start":"%d", "ncpus":"%.2f", "mem":"%s", "status":"R" }' % (int(time()), self.cpu_guarantee, self.mem_guarantee)
          data = message.encode('utf-8')
          self.send_acct(data, id)
          #data = '{ "start": "%d" }' % (int(time()))
          #data = data.encode('ascii')
          #req = request.Request(url=url, data=data, method='PUT')
          #req.add_header("Content-Type", "application/json")
          # TODO: catch errors and log
          # TODO: check response
          #request.urlopen(req)
          return r
      c.JupyterHub.spawner_class = MySpawner
      c.Spawner.options_form = """<label for='image'>Image</label>&nbsp;&nbsp;
        <select name='image'>
          <option value='0' selected='selected'>ZTF Notebook</option>
          <option value='1'>Standard Notebook</option>
          <option value='2'>Data Science Notebook</option>
        </select>&nbsp;&nbsp;&nbsp;
        <label for='size'>Size</label>&nbsp;&nbsp;
        <select name='size'>
          <option value='0'>Tiny (256M / 0.25 CPU)</option>
          <option value='1' selected='selected'>Small (1G / 1 CPU)</option>
          <option value='2'>Large (8G / 4 CPU)</option>
          <option value='3'>X-Large (24G / 12 CPU)</option>
        </select>"""
    # Custom hooks for accounting
    custom_acct: |
      from urllib import request
      from time import time
      import json
      def acct_start(spawner):
        #url = 'http://192.168.140.14:5000/job'
        username = spawner.user.name
        data = '{ "user": "%s", "ctime":"%d" }' % (username, int(time()))
        data = data.encode('utf-8')
        #req = request.Request(url=url, data=data, method='POST')
        #req.add_header("Content-Type", "application/json")
        resp = spawner.send_acct(data)
        # TODO: catch errors and log
        # TODO: check response code
        #with request.urlopen(req) as f:
        #  resp = json.loads(f.read(256).decode('utf-8'))
        if resp:
          resp = json.loads(resp)
          id = resp.get('id')
          spawner.environment['JOB_ID'] = str(id)
      c.Spawner.pre_spawn_hook = acct_start
      def acct_stop(spawner):
        id = spawner.environment['JOB_ID']
        #url = 'http://192.168.140.14:5000/job/%s' % (id)
        data = '{ "end":"%d", "status":"E" }' % (int(time()))
        data = data.encode('utf-8')
        #req = request.Request(url=url, data=data, method='PUT')
        #req.add_header("Content-Type", "application/json")
        resp = spawner.send_acct(data, id)
        # TODO: catch errors and log
        # TODO: check response
        #request.urlopen(req)
      c.Spawner.post_stop_hook = acct_stop
    # Custom authentictor for EGI Check-in
    # - Checks that edu_person_entitlements is set and includes required group
    # - Replaces "sub" with a 20 char hash (to avoid exceeding length restrictions in k8s)
    # - Sets environment variables for git
    custom_auth: |
      from tornado import gen
      from oauthenticator.generic import GenericOAuthenticator
      from re import match
      from hashlib import sha1
      from os import environ
      class MyOAuthenticator(GenericOAuthenticator):
        @gen.coroutine
        def authenticate(self, handler, data=None):
          _MY_GROUP = environ.get('MY_GROUP', '')
          userdict = yield super().authenticate(handler, data)
          if 'edu_person_entitlements' in userdict['auth_state']['oauth_user']:
            entitlements = userdict['auth_state']['oauth_user']['edu_person_entitlements']
            for ent in entitlements:
              if match(_MY_GROUP, ent):
                self.log.info("Allowing subject %s as member of group %s", userdict['name'], _MY_GROUP)
                break
            else:
              self.log.warning("Subject %s does not have required entitlements", userdict['name'])
              return None
          else:
            self.log.warning("Subject %s does not have required entitlements", userdict['name'])
            return None
          m = sha1()
          m.update(userdict['name'].encode('utf-8'))
          userdict['name'] = m.hexdigest()[:20]
          return userdict
        @gen.coroutine
        def pre_spawn_start(self, user, spawner):
          _MY_GROUP = environ.get('MY_GROUP', '')
          auth_state = yield user.get_auth_state()
          if not auth_state:
            self.log.warning("auth_state not available - custom environment variables will not be set")
            return
          fullname = ''
          email = ''
          if 'oauth_user' in auth_state:
            if 'name' in auth_state['oauth_user']:
              fullname += auth_state['oauth_user']['name']
            else:
              name = []
              if 'given_name' in auth_state['oauth_user']:
                name.append(auth_state['oauth_user']['given_name'])
              if 'family_name' in auth_state['oauth_user']:
                name.append(auth_state['oauth_user']['family_name'])
              fullname += ' '.join(name)
            email = auth_state['oauth_user'].get('email', '')
          spawner.environment['GIT_AUTHOR_NAME'] = fullname
          spawner.environment['GIT_COMMITTER_NAME'] = fullname
          spawner.environment['EMAIL'] = email
      c.JupyterHub.authenticator_class = MyOAuthenticator
      c.Authenticator.enable_auth_state = True
    # Specify a custom template path (works with custom hub image)
    custom_template: |
      c.JupyterHub.template_paths = ['/usr/local/share/jupyterhub/custom_templates']
